# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="monitor.proto",
    package="chec",
    syntax="proto2",
    serialized_options=None,
    serialized_pb=_b(
        '\n\rmonitor.proto\x12\x04\x63hec"$\n\x07TimeUTC\x12\x0b\n\x03sec\x18\x01 \x02(\x05\x12\x0c\n\x04nsec\x18\x02 \x02(\x05"\xa4\x01\n\x0bMonitorData\x12\x1b\n\x04time\x18\x01 \x02(\x0b\x32\r.chec.TimeUTC\x12+\n\x07reciver\x18\x10 \x01(\x0b\x32\x1a.chec.MonitorData.Reciever\x1aK\n\x08Reciever\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x05\x12\x11\n\trecv_data\x18\x03 \x01(\x08\x12\x11\n\tdata_rate\x18\x04 \x01(\x02"O\n\x0cMonitorFrame\x12\x1b\n\x04time\x18\x01 \x02(\x0b\x32\r.chec.TimeUTC\x12"\n\x07mondata\x18\x02 \x03(\x0b\x32\x11.chec.MonitorData'
    ),
)


_TIMEUTC = _descriptor.Descriptor(
    name="TimeUTC",
    full_name="chec.TimeUTC",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="sec",
            full_name="chec.TimeUTC.sec",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=2,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="nsec",
            full_name="chec.TimeUTC.nsec",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=2,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=23,
    serialized_end=59,
)


_MONITORDATA_RECIEVER = _descriptor.Descriptor(
    name="Reciever",
    full_name="chec.MonitorData.Reciever",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="chec.MonitorData.Reciever.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="pid",
            full_name="chec.MonitorData.Reciever.pid",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="recv_data",
            full_name="chec.MonitorData.Reciever.recv_data",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="data_rate",
            full_name="chec.MonitorData.Reciever.data_rate",
            index=3,
            number=4,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=151,
    serialized_end=226,
)

_MONITORDATA = _descriptor.Descriptor(
    name="MonitorData",
    full_name="chec.MonitorData",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="time",
            full_name="chec.MonitorData.time",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=2,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="reciver",
            full_name="chec.MonitorData.reciver",
            index=1,
            number=16,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[_MONITORDATA_RECIEVER],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=62,
    serialized_end=226,
)


_MONITORFRAME = _descriptor.Descriptor(
    name="MonitorFrame",
    full_name="chec.MonitorFrame",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="time",
            full_name="chec.MonitorFrame.time",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=2,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="mondata",
            full_name="chec.MonitorFrame.mondata",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=228,
    serialized_end=307,
)

_MONITORDATA_RECIEVER.containing_type = _MONITORDATA
_MONITORDATA.fields_by_name["time"].message_type = _TIMEUTC
_MONITORDATA.fields_by_name["reciver"].message_type = _MONITORDATA_RECIEVER
_MONITORFRAME.fields_by_name["time"].message_type = _TIMEUTC
_MONITORFRAME.fields_by_name["mondata"].message_type = _MONITORDATA
DESCRIPTOR.message_types_by_name["TimeUTC"] = _TIMEUTC
DESCRIPTOR.message_types_by_name["MonitorData"] = _MONITORDATA
DESCRIPTOR.message_types_by_name["MonitorFrame"] = _MONITORFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeUTC = _reflection.GeneratedProtocolMessageType(
    "TimeUTC",
    (_message.Message,),
    dict(
        DESCRIPTOR=_TIMEUTC,
        __module__="monitor_pb2"
        # @@protoc_insertion_point(class_scope:chec.TimeUTC)
    ),
)
_sym_db.RegisterMessage(TimeUTC)

MonitorData = _reflection.GeneratedProtocolMessageType(
    "MonitorData",
    (_message.Message,),
    dict(
        Reciever=_reflection.GeneratedProtocolMessageType(
            "Reciever",
            (_message.Message,),
            dict(
                DESCRIPTOR=_MONITORDATA_RECIEVER,
                __module__="monitor_pb2"
                # @@protoc_insertion_point(class_scope:chec.MonitorData.Reciever)
            ),
        ),
        DESCRIPTOR=_MONITORDATA,
        __module__="monitor_pb2"
        # @@protoc_insertion_point(class_scope:chec.MonitorData)
    ),
)
_sym_db.RegisterMessage(MonitorData)
_sym_db.RegisterMessage(MonitorData.Reciever)

MonitorFrame = _reflection.GeneratedProtocolMessageType(
    "MonitorFrame",
    (_message.Message,),
    dict(
        DESCRIPTOR=_MONITORFRAME,
        __module__="monitor_pb2"
        # @@protoc_insertion_point(class_scope:chec.MonitorFrame)
    ),
)
_sym_db.RegisterMessage(MonitorFrame)


# @@protoc_insertion_point(module_scope)
